name: bacmet

services:
  app:
    build:
      target: dev
    volumes:
      - ./app/app:/opt/bacmet/app

  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend/bacmet:/opt/bacmet/frontend
