name: bacmet

services:
  database:
    build:
      context: database
    environment:
      - DATABASE_REINIT
    volumes:
      - data:/data
      - ./data-import:/data-import:ro
    profiles: ["load-data"]

  app:
    build:
      context: app
      target: prod
    ports:
      - ${APP_HOST:-127.0.0.1}:${APP_PORT:-5000}:5000
    volumes:
      - data:/data

volumes:
  data:
